spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        profile-view: profile_view_channel
        mentorship-requested: mentorship_requested_channel
        post-view: post_view_channel
        comment: comment-event-channel
        like: like-event-channel
        completed-task: completed_task_channel
        project_views: project_views_channel

server:
  port: 8086

logging:
  level:
    root: info

internal-services:
  project-service:
    host: localhost
    port: 8082
  user-service:
    host: localhost
    port: 8080

external-services: